# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

ZoolanderQuote.create(body: "You can read minds?")
ZoolanderQuote.create(body: "I'm pretty sure there's a lot more to life than being really, really, ridiculously good looking.")
ZoolanderQuote.create(body: "It's that damn Hansel! He's so hot right now!")
ZoolanderQuote.create(body: "But why male models?")
ZoolanderQuote.create(body: "I'm sorry that good-looking people like us made you throw up and feel bad about yourself.")
ZoolanderQuote.create(body: "Moisture is the essence of wetness, and wetness is the essence of beauty.")
ZoolanderQuote.create(body: "A week? What, are you having a whack attack? I saw you this afternoon, dum-dum.")
ZoolanderQuote.create(body: "Or are you here to tell me what a bad eugoogoolizer I am?")
ZoolanderQuote.create(body: "I guess you can dere-lick my balls cap-E-tan.")
ZoolanderQuote.create(body: "Listen to your friend Billy Zane, he's a cool dude!")
ZoolanderQuote.create(body: "It's a walk-off!")
ZoolanderQuote.create(body: "Mer-man! [high-pitched cough] Mer-man!")
ZoolanderQuote.create(body: "You is talking loco and I like it!")
ZoolanderQuote.create(body: "Be professionally good looking.")
ZoolanderQuote.create(body: "Mugatu is so hot right now he could take a crap, wrap it in tinfoil, put a couple fish hooks on it and sell it to Queen Elizabeth as earrings.")
ZoolanderQuote.create(body: "Now, this'll be a straight walk-off, old school rules. First model walks; second model duplicates, then elaborates. Okay, boys - let's go to work!")
ZoolanderQuote.create(body: "I'm a hand model, mama. A finger jockey. We think differently than the face and body boys... we're a different breed.")
ZoolanderQuote.create(body: "You think that you're too cool for school, but I have a newsflash for you Walter Cronkite... you aren't.")
ZoolanderQuote.create(body: "How can we be expected to teach children to learn how to read if they can't even fit inside the building?")
ZoolanderQuote.create(body: "They're break-dance fighting.")
ZoolanderQuote.create(body: "A eugoogalizor, one who speaks at funerals. Or did you think I'd be too stupid to know what a eugoogoly was?")
ZoolanderQuote.create(body: "By the way, you were wrong about my outfit. It's the Cheryl Ladd collection and I got it at JC Penney's. On sale!")
ZoolanderQuote.create(body: "Now if you'll excuse me, I have an after-funeral party to attend.")
ZoolanderQuote.create(body: "Let me show you Derelicte. It is a fashion, a way of life inspired by the very homeless, the vagrants, the crack whores that make this wonderful city so unique.")
ZoolanderQuote.create(body: "Well I guess it all started the first time I went through the second grade. I caught my reflection in a spoon while I was eating my cereal, and I remember thinking 'wow, you're ridiculously good looking, maybe you could do that for a career.'")
ZoolanderQuote.create(body: "What say we settle this on the runway...Han-Solo?")
ZoolanderQuote.create(body: "You know, I love modelling. I'd like to do this forever. When I'm 30, I hope I'm still modeling.")
ZoolanderQuote.create(body: "What is this? A center for ants?!")
ZoolanderQuote.create(body: "I think I'm getting the black lung Pop.")
ZoolanderQuote.create(body: "Orange mocha frappuccino!")
ZoolanderQuote.create(body: "At the Derek Zoolander Center For Children Who Can't Read Good And Wanna Learn To Do Other Stuff Good Too, we teach you that there's more to life than being really, really ridiculously good-looking.")
ZoolanderQuote.create(body: "Todd! Are you not aware that I get farty and bloated with a foamy latte!?")
ZoolanderQuote.create(body: "They're IN the computer?")
